version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet         # Go vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - gosec         # Security-focused linter
  disable:
    - errcheck      # Too many false positives for deferred Close()
    - gocritic      # Too opinionated for this stage
    - bodyclose     # Covered by manual review
    - noctx         # Not critical for this project
    - sqlclosecheck # Covered by manual review
    - rowserrcheck  # Covered by manual review
    - copyloopvar   # Go 1.22+ handles this automatically
    - errname       # Not critical
    - errorlint     # Will be addressed in future refactor
    - forcetypeassert # Not critical
    - goconst       # Will be addressed in future refactor
    - revive        # Too many rules for initial setup

formatters:
  enable:
    - gofmt         # Check code formatting
    - goimports     # Check import formatting

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      
  govet:
    check-shadowing: true
    enable-all: true
    
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G307 # Deferring unsafe method (intentional pattern)
      
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint # We don't require justification for every nolint
      - unnamedResult # Named returns not always needed
      
  staticcheck:
    checks: ["all"]
    
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
        
issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocritic
        - funlen
        - dupl
        
    # Ignore long lines in comments (often URLs or examples)
    - linters:
        - lll
      source: "^//"
      
    # Allow shadowing in short functions
    - linters:
        - govet
      text: "shadow: declaration of \"err\""
      
  max-issues-per-linter: 0
  max-same-issues: 0
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
