run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - gocritic      # Advanced linter with many checks
    - gosec         # Security-focused linter
    - bodyclose     # Check HTTP response bodies are closed
    - noctx         # Find HTTP requests without context
    - sqlclosecheck # Check SQL rows/statements are closed
    - rowserrcheck  # Check SQL rows errors are checked
    - exportloopref # Check for loop variable references in goroutines
    - errname       # Check error names follow convention
    - errorlint     # Error wrapping issues
    - forcetypeassert # Find forced type assertions
    - goconst       # Find repeated strings that could be constants
    - revive        # Fast, configurable, extensible linter

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      
  govet:
    check-shadowing: true
    enable-all: true
    
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G307 # Deferring unsafe method (intentional pattern)
      
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint # We don't require justification for every nolint
      - unnamedResult # Named returns not always needed
      
  staticcheck:
    checks: ["all"]
    
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
        
issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocritic
        - funlen
        - dupl
        
    # Ignore long lines in comments (often URLs or examples)
    - linters:
        - lll
      source: "^//"
      
    # Allow shadowing in short functions
    - linters:
        - govet
      text: "shadow: declaration of \"err\""
      
  max-issues-per-linter: 0
  max-same-issues: 0
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
