package config
package config

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/joho/godotenv"
)

// Config holds all application configuration





































































































































































}	return defaultValue	}		return d		}			return defaultValue			log.Printf("Warning: Invalid duration value for %s: %s, using default: %s", key, value, defaultValue)		if err != nil {		d, err := time.ParseDuration(value)	if value := os.Getenv(key); value != "" {func getEnvDuration(key string, defaultValue time.Duration) time.Duration {}	return defaultValue	}		return f		}			return defaultValue			log.Printf("Warning: Invalid float value for %s: %s, using default: %f", key, value, defaultValue)		if err != nil {		f, err := strconv.ParseFloat(value, 64)	if value := os.Getenv(key); value != "" {func getEnvFloat(key string, defaultValue float64) float64 {}	return defaultValue	}		return i		}			return defaultValue			log.Printf("Warning: Invalid integer value for %s: %s, using default: %d", key, value, defaultValue)		if err != nil {		i, err := strconv.Atoi(value)	if value := os.Getenv(key); value != "" {func getEnvInt(key string, defaultValue int) int {}	return defaultValue	}		return b		}			return defaultValue			log.Printf("Warning: Invalid boolean value for %s: %s, using default: %v", key, value, defaultValue)		if err != nil {		b, err := strconv.ParseBool(value)	if value := os.Getenv(key); value != "" {func getEnvBool(key string, defaultValue bool) bool {}	return defaultValue	}		return value	if value := os.Getenv(key); value != "" {func getEnv(key, defaultValue string) string {// Helper functions}	)		c.DBHost, c.DBPort, c.DBUser, c.DBPassword, c.DBName, c.DBSSLMode,		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",	return fmt.Sprintf(	// PostgreSQL DSN	}		return c.DBPath	if c.DBType == "sqlite" {func (c *Config) GetDSN() string {// GetDSN returns the database connection string}	return c.DBType == "postgres"func (c *Config) IsPostgres() bool {// IsPostgres returns true if PostgreSQL is configured}	return nil	}		log.Printf("Warning: Private key not found at %s, will generate new key", c.PrivateKeyPath)	if _, err := os.Stat(c.PrivateKeyPath); os.IsNotExist(err) {	// Check if private key exists	}		return fmt.Errorf("tiers configuration file not found: %s", c.TiersConfigPath)	if _, err := os.Stat(c.TiersConfigPath); os.IsNotExist(err) {	// Check if tiers config existsfunc (c *Config) Validate() error {// Validate performs additional validation and setup}	return cfg, nil	}		return nil, fmt.Errorf("RESEND_API_KEY is required when REQUIRE_EMAIL_VERIFICATION=true")	if cfg.RequireEmailVerification && cfg.ResendAPIKey == "" {	}		return nil, fmt.Errorf("DB_PASSWORD is required for PostgreSQL")	if cfg.DBType == "postgres" && cfg.DBPassword == "" {	}		return nil, fmt.Errorf("DB_TYPE must be either 'sqlite' or 'postgres', got: %s", cfg.DBType)	if cfg.DBType != "sqlite" && cfg.DBType != "postgres" {	// Validate required settings	}		TiersConfigPath:          getEnv("TIERS_CONFIG", "tiers.toml"),		RateLimiterCleanup:       getEnvDuration("RATE_LIMITER_CLEANUP", 5*time.Minute),		RateLimitBurst:           getEnvInt("RATE_LIMIT_BURST", 20),		RateLimitPerSecond:       getEnvFloat("RATE_LIMIT_PER_SECOND", 10.0),		PrivateKeyPath:           getEnv("PRIVATE_KEY_PATH", "private.key"),		RequireEmailVerification: getEnvBool("REQUIRE_EMAIL_VERIFICATION", true),		FromName:                 getEnv("FROM_NAME", "Licensify"),		FromEmail:                getEnv("FROM_EMAIL", "noreply@yourdomain.com"),		ResendAPIKey:             getEnv("RESEND_API_KEY", ""),		DBSSLMode:                getEnv("DB_SSLMODE", "require"),		DBPassword:               getEnv("DB_PASSWORD", ""),		DBUser:                   getEnv("DB_USER", "licensify"),		DBName:                   getEnv("DB_NAME", "licensify"),		DBPort:                   getEnv("DB_PORT", "5432"),		DBHost:                   getEnv("DB_HOST", "localhost"),		DBPath:                   getEnv("DB_PATH", "licensify.db"),		DBType:                   getEnv("DB_TYPE", "sqlite"),		BaseURL:                  getEnv("BASE_URL", "http://localhost:8080"),		Port:                     getEnv("PORT", "8080"),	cfg := &Config{	_ = godotenv.Load()	// Load .env file if it exists (ignore error if it doesn't)func Load() (*Config, error) {// Load loads configuration from environment variables}	TiersConfigPath string	// Tiers configuration	RateLimiterCleanup time.Duration	RateLimitBurst     int	RateLimitPerSecond float64	// Rate limiting		PrivateKeyPath string	// Security settings	RequireEmailVerification bool	FromName     string	FromEmail    string	ResendAPIKey string	// Email settings	DBSSLMode  string // PostgreSQL only	DBPassword string // PostgreSQL only	DBUser     string // PostgreSQL only	DBName     string // PostgreSQL only	DBPort     string // PostgreSQL only	DBHost     string // PostgreSQL only	DBPath     string // SQLite only	DBType     string	// Database settings	BaseURL string	Port    string	// Server settingstype Config struct {